name: Deploy to develop enviroment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to develop
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Pull LFS objects
        run: git lfs pull

      - name: Deploy to develop
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
